_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 105
            "3":
                - 23
                - 55
            "4": 3.11.5
            "5": 0.18.6
            "6": 4.38.0.dev0
            "8":
                - 5
            "12": 0.18.6
            "13": linux-x86_64
